//
// Generated file, do not edit! Created by opp_msgc 4.3 from messages/Packet.msg.
//

#ifndef _PACKET_M_H_
#define _PACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/Packet.msg</tt> by opp_msgc.
 * <pre>
 * packet Packet
 * {
 *     int srcAddr;
 *     int dstAddr;
 *     int sessionId;
 *     int packetId = -1;
 *     int priority = 0;
 *     int clazz;
 *     int payload;
 * }
 * </pre>
 */
class Packet : public ::cPacket
{
  protected:
    int srcAddr_var;
    int dstAddr_var;
    int sessionId_var;
    int packetId_var;
    int priority_var;
    int clazz_var;
    int payload_var;

  private:
    void copy(const Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet&);

  public:
    Packet(const char *name=NULL, int kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const {return new Packet(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);
    virtual int getDstAddr() const;
    virtual void setDstAddr(int dstAddr);
    virtual int getSessionId() const;
    virtual void setSessionId(int sessionId);
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual int getClazz() const;
    virtual void setClazz(int clazz);
    virtual int getPayload() const;
    virtual void setPayload(int payload);
};

inline void doPacking(cCommBuffer *b, Packet& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


#endif // _PACKET_M_H_
